-- CreateTable
CREATE TABLE "FichaCadastral" (
    "id" SERIAL NOT NULL,
    "vehicleId" INTEGER NOT NULL,
    "marca" TEXT,
    "modelo" TEXT,
    "anoFabricacao" INTEGER,
    "anoModelo" INTEGER,
    "placa" TEXT,
    "chassi" TEXT,
    "renavam" TEXT,
    "cor" TEXT,
    "valor" DOUBLE PRECISION,
    "valorEntrada" DOUBLE PRECISION,
    "valorFinanciado" DOUBLE PRECISION,
    "parcelas" INTEGER,
    "valorParcela" DOUBLE PRECISION,
    "tipoPessoa" TEXT DEFAULT 'Física',
    "nomeCompleto" TEXT,
    "cpfCnpj" TEXT,
    "cnh" TEXT,
    "tipoCNH" TEXT,
    "dataEmissaoCNH" TIMESTAMP(3),
    "rg" TEXT,
    "orgaoEmissor" TEXT,
    "uf" TEXT,
    "dataEmissaoRG" TIMESTAMP(3),
    "dataNascimento" TIMESTAMP(3),
    "naturalidade" TEXT,
    "sexo" TEXT,
    "nomePai" TEXT,
    "nomeMae" TEXT,
    "estadoCivil" TEXT,
    "enderecoCorrespondencia" TEXT,
    "grauInstrucao" TEXT,
    "dependentes" INTEGER,
    "cep" TEXT,
    "endereco" TEXT,
    "numero" TEXT,
    "complemento" TEXT,
    "bairro" TEXT,
    "estado" TEXT,
    "cidade" TEXT,
    "tempoResidencia" TEXT,
    "tipoResidencia" TEXT,
    "telefoneResidencial" TEXT,
    "falarCom" TEXT,
    "tipoTelefone" TEXT,
    "telefoneCelular" TEXT,
    "email" TEXT,
    "empresa" TEXT,
    "cnpjEmpresa" TEXT,
    "rendaMensal" DOUBLE PRECISION,
    "rendaExtra" DOUBLE PRECISION,
    "rendaExtraOrigem" TEXT,
    "cargoFuncao" TEXT,
    "cepComercial" TEXT,
    "enderecoComercial" TEXT,
    "numeroComercial" TEXT,
    "complementoComercial" TEXT,
    "bairroComercial" TEXT,
    "ufComercial" TEXT,
    "cidadeComercial" TEXT,
    "telefoneComercial" TEXT,
    "tempoEmpresa" TEXT,
    "dataAdmissao" TIMESTAMP(3),
    "empresaAnterior" TEXT,
    "telefoneEmpresaAnterior" TEXT,
    "nomeConjuge" TEXT,
    "celularConjuge" TEXT,
    "cpfConjuge" TEXT,
    "rgConjuge" TEXT,
    "dataNascimentoConjuge" TIMESTAMP(3),
    "empresaConjuge" TEXT,
    "telefoneConjuge" TEXT,
    "ocupacaoConjuge" TEXT,
    "rendaConjuge" DOUBLE PRECISION,
    "referenciasPessoais" TEXT,
    "possuiCartaoCredito" TEXT,
    "referenciasBancarias" TEXT,
    "bensPessoais" TEXT,
    "vendedor" TEXT,
    "observacoes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FichaCadastral_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "FichaCadastral" ADD CONSTRAINT "FichaCadastral_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE CASCADE ON UPDATE CASCADE;
