-- AlterTable
ALTER TABLE "Vehicle" ADD COLUMN     "empresa" TEXT DEFAULT 'Iago Veiculos Ltda',
ADD COLUMN     "posicao" INTEGER,
ADD COLUMN     "conditionStatus" TEXT,
ADD COLUMN     "renavam" TEXT,
ADD COLUMN     "cadastroOutrasLojas" BOOLEAN DEFAULT false,
ADD COLUMN     "especie" TEXT,
ADD COLUMN     "combustivel" TEXT,
ADD COLUMN     "modeloDenatran" TEXT,
ADD COLUMN     "modeloBase" TEXT,
ADD COLUMN     "portas" TEXT,
ADD COLUMN     "carroceria" TEXT,
ADD COLUMN     "anoFabricacao" INTEGER,
ADD COLUMN     "anoModelo" INTEGER,
ADD COLUMN     "motorizacao" TEXT,
ADD COLUMN     "cambio" TEXT,
ADD COLUMN     "chassi" TEXT,
ADD COLUMN     "chassiRemarcado" BOOLEAN DEFAULT false,
ADD COLUMN     "modeloFipe" TEXT,
ADD COLUMN     "cidadeEmplacamento" TEXT,
ADD COLUMN     "numeroCambio" TEXT,
ADD COLUMN     "hpCv" TEXT,
ADD COLUMN     "periciaCautelar" TEXT,
ADD COLUMN     "passageiros" TEXT,
ADD COLUMN     "blindado" TEXT,
ADD COLUMN     "origem" TEXT,
ADD COLUMN     "numeroMotor" TEXT,
ADD COLUMN     "corInterna" TEXT,
ADD COLUMN     "opcionais" TEXT;
