// Opções para formulário de veículos

export const ESPECIES = [
  'AUTOMÓVEL',
  'CAMINHÃO',
  'CAMINHONETE',
  'MOTOCICLETA',
  'MOTONETA',
  'ONIBUS',
  'REBOQUE',
  'SEMIRREBOQUE',
  'TRICICLO',
  'OUTROS',
] as const

export const COMBUSTIVEIS = [
  'Álcool',
  'Diesel',
  'Flex (Álcool/Gasolina)',
  'Gasolina',
  'GNV',
  'Elétrico',
  'Híbrido',
  'Outros',
] as const

export const PORTAS = ['2', '3', '4', '5', 'Outros'] as const

export const CAMBIOS = [
  'Manual',
  'Automático',
  'Automático Sequencial',
  'CVT',
  'Dualogic',
  'Robotizado',
  'Outros',
] as const

export const BLINDADO = ['Sim', 'Não'] as const

export const ORIGEM = ['Nacional', 'Importado', 'Outros'] as const

export const PERICIA_CAUTELAR = ['Sim', 'Não', 'Em andamento'] as const

export const OPCIONAIS_LIST = [
  '4x4',
  '7 Lugares',
  'Abs',
  'Airbag',
  'Alarme',
  'Apoio De Braço',
  'Ar-condicionado',
  'Ar Quente',
  'Assistente De Rampa',
  'Bancos De Couro',
  'Câmbio Automático',
  'Câmbio Dualogic',
  'Câmbio Manual',
  'Desembaçador Traseiro',
  'Direção Elétrica',
  'Direção Hidráulica',
  'Limpador Traseiro',
  'Retrovisor Elétrico',
  'Rodas De Liga Leve',
  'Sensor De Estacionamento',
  'Som Multimídia',
  'Teto Solar',
  'Trava Elétrica',
  'Vidros Elétricos',
  '4x2',
  'Abs+ebd',
  'Abs+ebd+pba',
  'Adaptado Para Deficientes Físicos',
  'Aerofólio',
  'Airbag Cortina',
  'Airbag Duplo',
  'Airbag Lateral',
  'Alarme Inteligente',
  'Alerta De Colisão Frontal',
  'Alerta De Mudança De Faixa',
  'Alerta De Ponto Cego',
  'Amort. Direção',
  'Aquecimento Dos Bancos',
  'Ar-condicionado Digital',
  'Ar-condicionado Dual Zone',
  'Assistente De Permanência Em Faixa',
  'Auto Hold',
  'Bagageiro No Teto',
  'Banco Bipartido',
  'Banco Elétrico',
  'Banco Reclinável',
  'Bancos Com Memória De Regulagem',
  'Bancos Esportivos',
  'Bluelink',
  'Calotas',
  'Câmbio Automático Com Active Select',
  'Câmera 360 Graus',
  'Câmera De Ré',
  'Capota De Fibra',
  'Capota Marítima',
  'Cargo Box',
  'Carregador De Celular Por Indução',
  'Carregador Wireless',
  'Cd Controle No Volante',
  'Cd Player',
  'Chave Cópia/reserva',
  'Chave Presencial',
  'Com Passagem Por Leilão',
  'Computador De Bordo',
  'Console Central',
  'Console De Teto',
  'Controle De Estabilidade',
  'Controle De Tração',
  'Controle De Velocidade Adaptativo',
  'Controle Eletrônico Dos Amortecedores',
  'Descanso De Braço Central',
  'Direção Escamoteável',
  'Disqueteira',
  'Dvd',
  'Encosto De Cabeça Traseiro',
  'Engate',
  'Entrada Auxiliar',
  'Espelhamento De Celular',
  'Espelho Retrovisor Eletrocrômico',
  'Espelho Retrovisor Retrátil',
  'Estribo',
  'Farol De Led',
  'Farol De Milha',
  'Farol De Neblina',
  'Farol De Rodagem Diurna',
  'Farol De Xenon',
  'Freio A Disco Nas 2 Rodas',
  'Freio A Disco Nas 4 Rodas',
  'Freio De Mão Eletrônico',
  'Frenagem Automática De Emergência',
  'Frigobar',
  'Garantia De Fábrica',
  'Gps',
  'Insulfilm',
  'Ipva Pago',
  'Ipva Pago E Licenciado',
  'Isofix',
  'Isotérmico',
  'Keyless Entry System',
  'Kit Multimídia',
  'Licenciamento Pago',
  'Luz De Neblina Traseiro',
  'Magazine',
  'Manual Do Proprietário',
  'Mp3 Player',
  'Multi-lock',
  'My Link',
  'On Star',
  'Paddle Shift',
  'Painel Digital',
  'Park Assist',
  'Piloto Automático',
  'Porta Copos',
  'Porta-luvas Climatizado',
  'Porta Malas Elétrico',
  'Protetor De Caçamba',
  'Quebra-mato',
  'Rack No Teto',
  'Rádio Bluetooth',
  'Rastreador',
  'Regulagem Altura Do Banco',
  'Regulagem Elétrica Dos Faróis',
  'Retrovisor Com Rebatimento Eletrico',
  'Retrovisor Fotocrômico',
  'Revisões Em Dia',
  'Revisões Feitas Na Concessionária',
  'Santo Antônio',
  'Sensor De Chuva',
  'Sensor De Fadiga',
  'Sensor De Iluminação',
  'Sistema Drive Mode',
  'Sistema Stop/start',
  'Som',
  'Teto Sky Window',
  'Teto Solar Panoramico',
  'Touch Screen',
  'Trava Carneiro',
  'Trio Elétrico',
  'Turbo',
  'Único Dono',
  'Usb',
  'Vidros Elétricos Dianteiros',
  'Vidros Verdes',
  'Volante Com Multifunção',
  'Volante Com Regulagem De Altura',
  'Volante Com Regulagem De Altura E Profundidade',
]
